"""Module 4: Render note events into ASCII guitar tablature via Claude API."""
from typing import List, Dict
from pathlib import Path
import json
import os


def render_tab(note_events: List[Dict], bpm: int, grid: int, time_sig: str, output_path: str, title: str, url: str):
    tab_text = _generate_tab_with_claude(note_events, bpm, time_sig, title)

    out = Path(output_path)
    with out.open('w', encoding='utf8') as f:
        f.write(f"Song: {title}\n")
        f.write(f"URL: {url}\n")
        f.write(f"BPM: {bpm}\n")
        f.write(f"Time Signature: {time_sig}\n")
        f.write("Generated by: song-to-tab v2.0 (AI-powered)\n\n")
        f.write('--- TAB ---\n\n')
        f.write(tab_text)
        f.write('\n')


def render_tab_to_string(note_events: List[Dict], bpm: int, time_sig: str, title: str) -> str:
    return _generate_tab_with_claude(note_events, bpm, time_sig, title)


def _generate_tab_with_claude(note_events: List[Dict], bpm: int, time_sig: str, title: str) -> str:
    try:
        import anthropic
    except ImportError:
        raise RuntimeError("anthropic package not installed. Run: pip install anthropic")

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY environment variable not set")

    client = anthropic.Anthropic(api_key=api_key)

    # Take notes from the first 30 seconds — dense and consecutive gives Claude
    # enough context to produce readable tab without huge timing gaps
    notes_window = [e for e in note_events if e["onset_time"] <= 30.0]
    notes_to_send = notes_window[:150] if len(notes_window) > 150 else notes_window
    if not notes_to_send:
        notes_to_send = note_events[:150]

    notes_json = json.dumps([
        {"time": round(e["onset_time"], 3), "midi": e["pitch"], "duration": round(e["duration"], 3)}
        for e in notes_to_send
    ], indent=2)

    prompt = f"""You are a guitar transcription expert. Convert these MIDI note events into readable ASCII guitar tablature.

Song: {title}
BPM: {bpm}
Time Signature: {time_sig}

Note events (onset_time in seconds, midi pitch, duration in seconds):
{notes_json}

Rules:
- Standard tuning: E2=40, A2=45, D3=50, G3=55, B3=59, e4=64
- Map each MIDI pitch to a string and fret. Prefer positions that minimize hand movement.
- Notes with overlapping times are chords — place them in the same column.
- Format as standard ASCII tab: 6 lines labeled e, B, G, D, A, E (high to low), measures separated by |.
- IMPORTANT: Keep the tab COMPACT. Each measure should be 4 beats wide. Do not leave long stretches of empty dashes — if there are no notes in a beat, show one --- per beat, not dozens.
- Aim for 4 measures per line, then start a new set of 6 lines.
- Fret numbers replace dashes. Two-digit frets (e.g. 12) are fine.
- Output ONLY the tab lines, no explanation or preamble."""

    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}]
    )

    return message.content[0].text
