"""Module 4: Render note events into ASCII guitar tablature."""
from typing import List, Dict
from pathlib import Path
from utils.midi_utils import map_midi_to_string_fret, STANDARD_TUNING_STRINGS


def render_tab(note_events: List[Dict], bpm: int, grid: int, time_sig: str, output_path: str, title: str, url: str):
    # Parse time signature
    try:
        numerator, denominator = time_sig.split('/')
        numerator = int(numerator)
        denominator = int(denominator)
    except Exception:
        numerator, denominator = 4, 4

    subdivisions_per_measure = grid
    subdivisions_per_beat = int(grid / numerator)
    secs_per_beat = 60.0 / float(bpm)
    secs_per_subdiv = secs_per_beat / subdivisions_per_beat

    # Quantize events to subdivision indices
    positions = []  # list of tuples (pos_index, string, fret)
    max_pos = 0
    for ev in note_events:
        pos = int(round(ev['onset_time'] / secs_per_subdiv))
        midi = int(ev['pitch'])
        mapping = map_midi_to_string_fret(midi)
        if mapping is None:
            continue
        string_idx, fret = mapping
        positions.append((pos, string_idx, fret))
        if pos > max_pos:
            max_pos = pos

    # Build grid: number of measures
    if max_pos == 0:
        max_pos = 1
    total_subdivs = max_pos + 1
    measures = (total_subdivs + subdivisions_per_measure - 1) // subdivisions_per_measure

    # Prepare lines for 6 strings (index 0 = high e for display)
    # STANDARD_TUNING_STRINGS is [40,45,50,55,59,64] from low E to high e
    # We'll render top line as high e
    strings = ['e','B','G','D','A','E']
    line_grids = {s: ['-' for _ in range(measures * subdivisions_per_measure)] for s in strings}

    for pos, string_idx, fret in positions:
        # map string_idx (0 = low E) to display index
        display_idx = 5 - string_idx
        sname = strings[display_idx]
        cell = str(fret)
        # place fret number starting at pos (overwrite '-' with number)
        line_grids[sname][pos] = cell

    # Convert to ascii measures
    lines = []
    for s in strings:
        parts = []
        for m in range(measures):
            start = m*subdivisions_per_measure
            end = start + subdivisions_per_measure
            seg = line_grids[s][start:end]
            parts.append(''.join([pad_cell(c) for c in seg]))
        lines.append(f"{s} |" + '|'.join(parts) + '|')

    # Footer beat numbers for first measure only (simple)
    footer = ''
    beat_marks = []
    for b in range(numerator):
        beat_pos = b * subdivisions_per_beat
        beat_marks.append(str((b+1)))
    footer = ' '.join(beat_marks)

    # Write to file
    out = Path(output_path)
    with out.open('w', encoding='utf8') as f:
        f.write(f"Song: {title}\n")
        f.write(f"URL: {url}\n")
        f.write(f"BPM: {bpm}\n")
        f.write(f"Time Signature: {time_sig}\n")
        f.write("Generated by: song-to-tab v1.0\n\n")
        f.write('--- TAB ---\n\n')
        for l in lines:
            f.write(l + '\n')
        f.write('\n')
        f.write(' '.join(['   ' for _ in range(numerator)]) + '\n')


def pad_cell(c: str) -> str:
    # pad single or multi-digit fret numbers into 3-char wide cell for readability
    if c == '-':
        return '---'
    if len(c) == 1:
        return '-' + c + '-'
    if len(c) == 2:
        return c + '-'
    return c[:3]
